language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run build
env:
  - PUBLIC_PATH=/browser-editor/
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master